/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#0f1c30",
        "on-secondary-fixed-variant": "#653e00",
        "surface-bright": "#f9f9f6",
        champagne: "#FFD18C",
        "on-primary-container": "#7a869f",
        "on-tertiary-fixed-variant": "#5f4108",
        "surface-variant": "#e2e3e0",
        "primary-fixed-dim": "#bbc7e1",
        primary: "#000411",
        "inverse-primary": "#bbc7e1",
        "surface-container-high": "#e8e8e5",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#3b475d",
        secondary: "#865300",
        "secondary-fixed": "#ffddb8",
        tertiary: "#090400",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        "tertiary-container": "#2b1b00",
        "on-background": "#1a1c1b",
        "on-error": "#ffffff",
        "inverse-surface": "#2f312f",
        "primary-container": "#121e32",
        "secondary-container": "#fdaa37",
        "surface-tint": "#535f76",
        "surface-container-highest": "#e2e3e0",
        "on-surface-variant": "#45474d",
        "on-surface": "#1a1c1b",
        "on-error-container": "#93000a",
        "outline-variant": "#c5c6cd",
        surface: "#f9f9f6",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#ffddae",
        "surface-container": "#eeeeeb",
        background: "#f9f9f6",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#6b4200",
        "inverse-on-surface": "#f1f1ee",
        "deep-navy": "#121E32",
        "on-secondary-fixed": "#2b1700",
        "on-tertiary-fixed": "#281800",
        "error-container": "#ffdad6",
        "surface-container-low": "#f4f4f1",
        "off-white": "#F8F8F5",
        outline: "#75777d",
        "ambassador-gold": "#DC8F1A",
        charcoal: "#2D2D2D",
        "on-tertiary-container": "#a57f43",
        "surface-dim": "#dadad7",
        "tertiary-fixed-dim": "#ecbf7c",
        "secondary-fixed-dim": "#ffb960",
        "primary-fixed": "#d7e3fe",
      },
      fontFamily: {
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg-mobile": ["EB Garamond", "serif"],
        "headline-md": ["EB Garamond", "serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["Hanken Grotesk", "sans-serif"],
        "headline-md-mobile": ["EB Garamond", "serif"],
        "display-lg": ["EB Garamond", "serif"],
        "title-lg": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg-mobile": [
          "40px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "500" },
        ],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" },
        ],
        "headline-md-mobile": [
          "28px",
          { lineHeight: "1.3", fontWeight: "500" },
        ],
        "display-lg": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "500" },
        ],
        "title-lg": [
          "20px",
          { lineHeight: "1.5", letterSpacing: "0.05em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};
